### ISSUE TITLE
docs/el-training.mdファイルを置き換えてください

### ISSUE THREAD

**Issue by suruseas** [sugataka1988/tasukun#4]
markdownではないHTMLファイルが格納されているので置き換えてください！

https://github.com/everyleaf/el-training/blob/master/README.md

**Comment by sugataka1988** [comment]
PRを作成しました！
お時間のある時に確認をお願いします！

**Comment by suruseas** [comment]
ご対応ありがとうございます。

今後は以下のように対象PRがわかりやすいように返信してください！

```
PRを作成しました！
https://github.com/sugataka1988/tasukun/pull/5

お時間のある時に確認をお願いします！
```

**Comment by sugataka1988** [comment]
完了！
